import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/styles/globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="overflow-hidden">
        <div className="flex">
          <Sidebar />

          <div className="flex flex-col w-full">
            <Header />

            <main className="bg-zinc-50 text-zinc-900 h-[calc(100vh-64px)] overflow-y-auto">
              {children}
            </main>
          </div>
        </div>

        <ToastContainer position="bottom-left" autoClose={2000} />
      </body>
    </html>
  );
}
