import "./globals.css";

// local font
import LocalFont from "next/font/local";

// remote font
import { Oswald } from "next/font/google";
import Header from "@/components/Header";

// remote font kurulum
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-oswald",
});

// local font kurulum
const singsong = LocalFont({
  src: "../assets/singsong.otf",
  variable: "--font-singsong",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased ${oswald.variable} ${singsong.variable}`}>
      <body className={`min-h-full flex flex-col`}>
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
